// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0--rc2
// source: ironhost/v1/agent.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to create a new game server container
type CreateServerRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ServerId string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Name     string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Docker image - defaults to itzg/minecraft-server if not specified
	DockerImage string `protobuf:"bytes,3,opt,name=docker_image,json=dockerImage,proto3" json:"docker_image,omitempty"`
	// Resource limits
	Limits *ResourceLimits `protobuf:"bytes,4,opt,name=limits,proto3" json:"limits,omitempty"`
	// Port allocations
	Allocations []*Allocation `protobuf:"bytes,5,rep,name=allocations,proto3" json:"allocations,omitempty"`
	// Environment variables (includes TYPE for server type, e.g., TYPE=LEAF)
	Environment []*EnvVar `protobuf:"bytes,6,rep,name=environment,proto3" json:"environment,omitempty"`
	// Volume mount path on host
	DataDirectory string `protobuf:"bytes,7,opt,name=data_directory,json=dataDirectory,proto3" json:"data_directory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateServerRequest) Reset() {
	*x = CreateServerRequest{}
	mi := &file_ironhost_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServerRequest) ProtoMessage() {}

func (x *CreateServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ironhost_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServerRequest.ProtoReflect.Descriptor instead.
func (*CreateServerRequest) Descriptor() ([]byte, []int) {
	return file_ironhost_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *CreateServerRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *CreateServerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateServerRequest) GetDockerImage() string {
	if x != nil {
		return x.DockerImage
	}
	return ""
}

func (x *CreateServerRequest) GetLimits() *ResourceLimits {
	if x != nil {
		return x.Limits
	}
	return nil
}

func (x *CreateServerRequest) GetAllocations() []*Allocation {
	if x != nil {
		return x.Allocations
	}
	return nil
}

func (x *CreateServerRequest) GetEnvironment() []*EnvVar {
	if x != nil {
		return x.Environment
	}
	return nil
}

func (x *CreateServerRequest) GetDataDirectory() string {
	if x != nil {
		return x.DataDirectory
	}
	return ""
}

type CreateServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ContainerId   string                 `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateServerResponse) Reset() {
	*x = CreateServerResponse{}
	mi := &file_ironhost_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServerResponse) ProtoMessage() {}

func (x *CreateServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ironhost_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServerResponse.ProtoReflect.Descriptor instead.
func (*CreateServerResponse) Descriptor() ([]byte, []int) {
	return file_ironhost_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *CreateServerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateServerResponse) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *CreateServerResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type StopServerRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ServerId       string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,2,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"` // Graceful shutdown timeout
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StopServerRequest) Reset() {
	*x = StopServerRequest{}
	mi := &file_ironhost_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopServerRequest) ProtoMessage() {}

func (x *StopServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ironhost_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopServerRequest.ProtoReflect.Descriptor instead.
func (*StopServerRequest) Descriptor() ([]byte, []int) {
	return file_ironhost_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *StopServerRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *StopServerRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type ServerActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerActionResponse) Reset() {
	*x = ServerActionResponse{}
	mi := &file_ironhost_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerActionResponse) ProtoMessage() {}

func (x *ServerActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ironhost_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerActionResponse.ProtoReflect.Descriptor instead.
func (*ServerActionResponse) Descriptor() ([]byte, []int) {
	return file_ironhost_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *ServerActionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ServerActionResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ListServersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Servers       []*ServerState         `protobuf:"bytes,1,rep,name=servers,proto3" json:"servers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServersResponse) Reset() {
	*x = ListServersResponse{}
	mi := &file_ironhost_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServersResponse) ProtoMessage() {}

func (x *ListServersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ironhost_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServersResponse.ProtoReflect.Descriptor instead.
func (*ListServersResponse) Descriptor() ([]byte, []int) {
	return file_ironhost_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *ListServersResponse) GetServers() []*ServerState {
	if x != nil {
		return x.Servers
	}
	return nil
}

type ConsoleOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Line          string                 `protobuf:"bytes,2,opt,name=line,proto3" json:"line,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	IsError       bool                   `protobuf:"varint,4,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsoleOutput) Reset() {
	*x = ConsoleOutput{}
	mi := &file_ironhost_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsoleOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsoleOutput) ProtoMessage() {}

func (x *ConsoleOutput) ProtoReflect() protoreflect.Message {
	mi := &file_ironhost_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsoleOutput.ProtoReflect.Descriptor instead.
func (*ConsoleOutput) Descriptor() ([]byte, []int) {
	return file_ironhost_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *ConsoleOutput) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ConsoleOutput) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

func (x *ConsoleOutput) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ConsoleOutput) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

type SendCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendCommandRequest) Reset() {
	*x = SendCommandRequest{}
	mi := &file_ironhost_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCommandRequest) ProtoMessage() {}

func (x *SendCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ironhost_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCommandRequest.ProtoReflect.Descriptor instead.
func (*SendCommandRequest) Descriptor() ([]byte, []int) {
	return file_ironhost_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *SendCommandRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *SendCommandRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type NodeStats struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	NodeId               string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	TotalMemoryBytes     int64                  `protobuf:"varint,2,opt,name=total_memory_bytes,json=totalMemoryBytes,proto3" json:"total_memory_bytes,omitempty"`
	AvailableMemoryBytes int64                  `protobuf:"varint,3,opt,name=available_memory_bytes,json=availableMemoryBytes,proto3" json:"available_memory_bytes,omitempty"`
	TotalDiskBytes       int64                  `protobuf:"varint,4,opt,name=total_disk_bytes,json=totalDiskBytes,proto3" json:"total_disk_bytes,omitempty"`
	AvailableDiskBytes   int64                  `protobuf:"varint,5,opt,name=available_disk_bytes,json=availableDiskBytes,proto3" json:"available_disk_bytes,omitempty"`
	CpuUsagePercent      float64                `protobuf:"fixed64,6,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`
	RunningContainers    int32                  `protobuf:"varint,7,opt,name=running_containers,json=runningContainers,proto3" json:"running_containers,omitempty"`
	UptimeSeconds        int64                  `protobuf:"varint,8,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *NodeStats) Reset() {
	*x = NodeStats{}
	mi := &file_ironhost_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStats) ProtoMessage() {}

func (x *NodeStats) ProtoReflect() protoreflect.Message {
	mi := &file_ironhost_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStats.ProtoReflect.Descriptor instead.
func (*NodeStats) Descriptor() ([]byte, []int) {
	return file_ironhost_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *NodeStats) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeStats) GetTotalMemoryBytes() int64 {
	if x != nil {
		return x.TotalMemoryBytes
	}
	return 0
}

func (x *NodeStats) GetAvailableMemoryBytes() int64 {
	if x != nil {
		return x.AvailableMemoryBytes
	}
	return 0
}

func (x *NodeStats) GetTotalDiskBytes() int64 {
	if x != nil {
		return x.TotalDiskBytes
	}
	return 0
}

func (x *NodeStats) GetAvailableDiskBytes() int64 {
	if x != nil {
		return x.AvailableDiskBytes
	}
	return 0
}

func (x *NodeStats) GetCpuUsagePercent() float64 {
	if x != nil {
		return x.CpuUsagePercent
	}
	return 0
}

func (x *NodeStats) GetRunningContainers() int32 {
	if x != nil {
		return x.RunningContainers
	}
	return 0
}

func (x *NodeStats) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_ironhost_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ironhost_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_ironhost_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *PingResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *PingResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PingResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_ironhost_v1_agent_proto protoreflect.FileDescriptor

const file_ironhost_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x17ironhost/v1/agent.proto\x12\vironhost.v1\x1a\x18ironhost/v1/common.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xb7\x02\n" +
	"\x13CreateServerRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fdocker_image\x18\x03 \x01(\tR\vdockerImage\x123\n" +
	"\x06limits\x18\x04 \x01(\v2\x1b.ironhost.v1.ResourceLimitsR\x06limits\x129\n" +
	"\vallocations\x18\x05 \x03(\v2\x17.ironhost.v1.AllocationR\vallocations\x125\n" +
	"\venvironment\x18\x06 \x03(\v2\x13.ironhost.v1.EnvVarR\venvironment\x12%\n" +
	"\x0edata_directory\x18\a \x01(\tR\rdataDirectory\"x\n" +
	"\x14CreateServerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\fcontainer_id\x18\x02 \x01(\tR\vcontainerId\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"Y\n" +
	"\x11StopServerRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12'\n" +
	"\x0ftimeout_seconds\x18\x02 \x01(\x05R\x0etimeoutSeconds\"U\n" +
	"\x14ServerActionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"I\n" +
	"\x13ListServersResponse\x122\n" +
	"\aservers\x18\x01 \x03(\v2\x18.ironhost.v1.ServerStateR\aservers\"y\n" +
	"\rConsoleOutput\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x12\n" +
	"\x04line\x18\x02 \x01(\tR\x04line\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x19\n" +
	"\bis_error\x18\x04 \x01(\bR\aisError\"K\n" +
	"\x12SendCommandRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\"\xe6\x02\n" +
	"\tNodeStats\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12,\n" +
	"\x12total_memory_bytes\x18\x02 \x01(\x03R\x10totalMemoryBytes\x124\n" +
	"\x16available_memory_bytes\x18\x03 \x01(\x03R\x14availableMemoryBytes\x12(\n" +
	"\x10total_disk_bytes\x18\x04 \x01(\x03R\x0etotalDiskBytes\x120\n" +
	"\x14available_disk_bytes\x18\x05 \x01(\x03R\x12availableDiskBytes\x12*\n" +
	"\x11cpu_usage_percent\x18\x06 \x01(\x01R\x0fcpuUsagePercent\x12-\n" +
	"\x12running_containers\x18\a \x01(\x05R\x11runningContainers\x12%\n" +
	"\x0euptime_seconds\x18\b \x01(\x03R\ruptimeSeconds\"_\n" +
	"\fPingResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp2\xd0\x06\n" +
	"\fAgentService\x12S\n" +
	"\fCreateServer\x12 .ironhost.v1.CreateServerRequest\x1a!.ironhost.v1.CreateServerResponse\x12O\n" +
	"\vStartServer\x12\x1d.ironhost.v1.ServerIdentifier\x1a!.ironhost.v1.ServerActionResponse\x12O\n" +
	"\n" +
	"StopServer\x12\x1e.ironhost.v1.StopServerRequest\x1a!.ironhost.v1.ServerActionResponse\x12Q\n" +
	"\rRestartServer\x12\x1d.ironhost.v1.ServerIdentifier\x1a!.ironhost.v1.ServerActionResponse\x12P\n" +
	"\fDeleteServer\x12\x1d.ironhost.v1.ServerIdentifier\x1a!.ironhost.v1.ServerActionResponse\x12J\n" +
	"\x0fGetServerStatus\x12\x1d.ironhost.v1.ServerIdentifier\x1a\x18.ironhost.v1.ServerState\x12G\n" +
	"\vListServers\x12\x16.google.protobuf.Empty\x1a .ironhost.v1.ListServersResponse\x12L\n" +
	"\rStreamConsole\x12\x1d.ironhost.v1.ServerIdentifier\x1a\x1a.ironhost.v1.ConsoleOutput0\x01\x12F\n" +
	"\vSendCommand\x12\x1f.ironhost.v1.SendCommandRequest\x1a\x16.google.protobuf.Empty\x12>\n" +
	"\fGetNodeStats\x12\x16.google.protobuf.Empty\x1a\x16.ironhost.v1.NodeStats\x129\n" +
	"\x04Ping\x12\x16.google.protobuf.Empty\x1a\x19.ironhost.v1.PingResponseB'Z%github.com/ironhost/proto/ironhost/v1b\x06proto3"

var (
	file_ironhost_v1_agent_proto_rawDescOnce sync.Once
	file_ironhost_v1_agent_proto_rawDescData []byte
)

func file_ironhost_v1_agent_proto_rawDescGZIP() []byte {
	file_ironhost_v1_agent_proto_rawDescOnce.Do(func() {
		file_ironhost_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ironhost_v1_agent_proto_rawDesc), len(file_ironhost_v1_agent_proto_rawDesc)))
	})
	return file_ironhost_v1_agent_proto_rawDescData
}

var file_ironhost_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_ironhost_v1_agent_proto_goTypes = []any{
	(*CreateServerRequest)(nil),  // 0: ironhost.v1.CreateServerRequest
	(*CreateServerResponse)(nil), // 1: ironhost.v1.CreateServerResponse
	(*StopServerRequest)(nil),    // 2: ironhost.v1.StopServerRequest
	(*ServerActionResponse)(nil), // 3: ironhost.v1.ServerActionResponse
	(*ListServersResponse)(nil),  // 4: ironhost.v1.ListServersResponse
	(*ConsoleOutput)(nil),        // 5: ironhost.v1.ConsoleOutput
	(*SendCommandRequest)(nil),   // 6: ironhost.v1.SendCommandRequest
	(*NodeStats)(nil),            // 7: ironhost.v1.NodeStats
	(*PingResponse)(nil),         // 8: ironhost.v1.PingResponse
	(*ResourceLimits)(nil),       // 9: ironhost.v1.ResourceLimits
	(*Allocation)(nil),           // 10: ironhost.v1.Allocation
	(*EnvVar)(nil),               // 11: ironhost.v1.EnvVar
	(*ServerState)(nil),          // 12: ironhost.v1.ServerState
	(*ServerIdentifier)(nil),     // 13: ironhost.v1.ServerIdentifier
	(*emptypb.Empty)(nil),        // 14: google.protobuf.Empty
}
var file_ironhost_v1_agent_proto_depIdxs = []int32{
	9,  // 0: ironhost.v1.CreateServerRequest.limits:type_name -> ironhost.v1.ResourceLimits
	10, // 1: ironhost.v1.CreateServerRequest.allocations:type_name -> ironhost.v1.Allocation
	11, // 2: ironhost.v1.CreateServerRequest.environment:type_name -> ironhost.v1.EnvVar
	12, // 3: ironhost.v1.ListServersResponse.servers:type_name -> ironhost.v1.ServerState
	0,  // 4: ironhost.v1.AgentService.CreateServer:input_type -> ironhost.v1.CreateServerRequest
	13, // 5: ironhost.v1.AgentService.StartServer:input_type -> ironhost.v1.ServerIdentifier
	2,  // 6: ironhost.v1.AgentService.StopServer:input_type -> ironhost.v1.StopServerRequest
	13, // 7: ironhost.v1.AgentService.RestartServer:input_type -> ironhost.v1.ServerIdentifier
	13, // 8: ironhost.v1.AgentService.DeleteServer:input_type -> ironhost.v1.ServerIdentifier
	13, // 9: ironhost.v1.AgentService.GetServerStatus:input_type -> ironhost.v1.ServerIdentifier
	14, // 10: ironhost.v1.AgentService.ListServers:input_type -> google.protobuf.Empty
	13, // 11: ironhost.v1.AgentService.StreamConsole:input_type -> ironhost.v1.ServerIdentifier
	6,  // 12: ironhost.v1.AgentService.SendCommand:input_type -> ironhost.v1.SendCommandRequest
	14, // 13: ironhost.v1.AgentService.GetNodeStats:input_type -> google.protobuf.Empty
	14, // 14: ironhost.v1.AgentService.Ping:input_type -> google.protobuf.Empty
	1,  // 15: ironhost.v1.AgentService.CreateServer:output_type -> ironhost.v1.CreateServerResponse
	3,  // 16: ironhost.v1.AgentService.StartServer:output_type -> ironhost.v1.ServerActionResponse
	3,  // 17: ironhost.v1.AgentService.StopServer:output_type -> ironhost.v1.ServerActionResponse
	3,  // 18: ironhost.v1.AgentService.RestartServer:output_type -> ironhost.v1.ServerActionResponse
	3,  // 19: ironhost.v1.AgentService.DeleteServer:output_type -> ironhost.v1.ServerActionResponse
	12, // 20: ironhost.v1.AgentService.GetServerStatus:output_type -> ironhost.v1.ServerState
	4,  // 21: ironhost.v1.AgentService.ListServers:output_type -> ironhost.v1.ListServersResponse
	5,  // 22: ironhost.v1.AgentService.StreamConsole:output_type -> ironhost.v1.ConsoleOutput
	14, // 23: ironhost.v1.AgentService.SendCommand:output_type -> google.protobuf.Empty
	7,  // 24: ironhost.v1.AgentService.GetNodeStats:output_type -> ironhost.v1.NodeStats
	8,  // 25: ironhost.v1.AgentService.Ping:output_type -> ironhost.v1.PingResponse
	15, // [15:26] is the sub-list for method output_type
	4,  // [4:15] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_ironhost_v1_agent_proto_init() }
func file_ironhost_v1_agent_proto_init() {
	if File_ironhost_v1_agent_proto != nil {
		return
	}
	file_ironhost_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ironhost_v1_agent_proto_rawDesc), len(file_ironhost_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ironhost_v1_agent_proto_goTypes,
		DependencyIndexes: file_ironhost_v1_agent_proto_depIdxs,
		MessageInfos:      file_ironhost_v1_agent_proto_msgTypes,
	}.Build()
	File_ironhost_v1_agent_proto = out.File
	file_ironhost_v1_agent_proto_goTypes = nil
	file_ironhost_v1_agent_proto_depIdxs = nil
}
