// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0--rc2
// source: ironhost/v1/common.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Server status enum
type ServerStatus int32

const (
	ServerStatus_SERVER_STATUS_UNSPECIFIED ServerStatus = 0
	ServerStatus_SERVER_STATUS_INSTALLING  ServerStatus = 1
	ServerStatus_SERVER_STATUS_OFFLINE     ServerStatus = 2
	ServerStatus_SERVER_STATUS_STARTING    ServerStatus = 3
	ServerStatus_SERVER_STATUS_RUNNING     ServerStatus = 4
	ServerStatus_SERVER_STATUS_STOPPING    ServerStatus = 5
	ServerStatus_SERVER_STATUS_SUSPENDED   ServerStatus = 6
)

// Enum value maps for ServerStatus.
var (
	ServerStatus_name = map[int32]string{
		0: "SERVER_STATUS_UNSPECIFIED",
		1: "SERVER_STATUS_INSTALLING",
		2: "SERVER_STATUS_OFFLINE",
		3: "SERVER_STATUS_STARTING",
		4: "SERVER_STATUS_RUNNING",
		5: "SERVER_STATUS_STOPPING",
		6: "SERVER_STATUS_SUSPENDED",
	}
	ServerStatus_value = map[string]int32{
		"SERVER_STATUS_UNSPECIFIED": 0,
		"SERVER_STATUS_INSTALLING":  1,
		"SERVER_STATUS_OFFLINE":     2,
		"SERVER_STATUS_STARTING":    3,
		"SERVER_STATUS_RUNNING":     4,
		"SERVER_STATUS_STOPPING":    5,
		"SERVER_STATUS_SUSPENDED":   6,
	}
)

func (x ServerStatus) Enum() *ServerStatus {
	p := new(ServerStatus)
	*p = x
	return p
}

func (x ServerStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServerStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_ironhost_v1_common_proto_enumTypes[0].Descriptor()
}

func (ServerStatus) Type() protoreflect.EnumType {
	return &file_ironhost_v1_common_proto_enumTypes[0]
}

func (x ServerStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServerStatus.Descriptor instead.
func (ServerStatus) EnumDescriptor() ([]byte, []int) {
	return file_ironhost_v1_common_proto_rawDescGZIP(), []int{0}
}

type ServerIdentifier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerIdentifier) Reset() {
	*x = ServerIdentifier{}
	mi := &file_ironhost_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerIdentifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerIdentifier) ProtoMessage() {}

func (x *ServerIdentifier) ProtoReflect() protoreflect.Message {
	mi := &file_ironhost_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerIdentifier.ProtoReflect.Descriptor instead.
func (*ServerIdentifier) Descriptor() ([]byte, []int) {
	return file_ironhost_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *ServerIdentifier) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

type NodeIdentifier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeIdentifier) Reset() {
	*x = NodeIdentifier{}
	mi := &file_ironhost_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeIdentifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeIdentifier) ProtoMessage() {}

func (x *NodeIdentifier) ProtoReflect() protoreflect.Message {
	mi := &file_ironhost_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeIdentifier.ProtoReflect.Descriptor instead.
func (*NodeIdentifier) Descriptor() ([]byte, []int) {
	return file_ironhost_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *NodeIdentifier) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

// Resource limits for a game server container
type ResourceLimits struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemoryMb      int64                  `protobuf:"varint,1,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`       // Memory limit in MB
	DiskMb        int64                  `protobuf:"varint,2,opt,name=disk_mb,json=diskMb,proto3" json:"disk_mb,omitempty"`             // Disk limit in MB
	CpuPercent    int32                  `protobuf:"varint,3,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"` // CPU limit as percentage (100 = 1 core)
	IoWeight      int32                  `protobuf:"varint,4,opt,name=io_weight,json=ioWeight,proto3" json:"io_weight,omitempty"`       // Block IO weight (10-1000)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceLimits) Reset() {
	*x = ResourceLimits{}
	mi := &file_ironhost_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceLimits) ProtoMessage() {}

func (x *ResourceLimits) ProtoReflect() protoreflect.Message {
	mi := &file_ironhost_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceLimits.ProtoReflect.Descriptor instead.
func (*ResourceLimits) Descriptor() ([]byte, []int) {
	return file_ironhost_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *ResourceLimits) GetMemoryMb() int64 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *ResourceLimits) GetDiskMb() int64 {
	if x != nil {
		return x.DiskMb
	}
	return 0
}

func (x *ResourceLimits) GetCpuPercent() int32 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *ResourceLimits) GetIoWeight() int32 {
	if x != nil {
		return x.IoWeight
	}
	return 0
}

// Port allocation for a server
type Allocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IpAddress     string                 `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	IsPrimary     bool                   `protobuf:"varint,4,opt,name=is_primary,json=isPrimary,proto3" json:"is_primary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Allocation) Reset() {
	*x = Allocation{}
	mi := &file_ironhost_v1_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Allocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Allocation) ProtoMessage() {}

func (x *Allocation) ProtoReflect() protoreflect.Message {
	mi := &file_ironhost_v1_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Allocation.ProtoReflect.Descriptor instead.
func (*Allocation) Descriptor() ([]byte, []int) {
	return file_ironhost_v1_common_proto_rawDescGZIP(), []int{3}
}

func (x *Allocation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Allocation) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *Allocation) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Allocation) GetIsPrimary() bool {
	if x != nil {
		return x.IsPrimary
	}
	return false
}

// Environment variable for container
type EnvVar struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvVar) Reset() {
	*x = EnvVar{}
	mi := &file_ironhost_v1_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvVar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvVar) ProtoMessage() {}

func (x *EnvVar) ProtoReflect() protoreflect.Message {
	mi := &file_ironhost_v1_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvVar.ProtoReflect.Descriptor instead.
func (*EnvVar) Descriptor() ([]byte, []int) {
	return file_ironhost_v1_common_proto_rawDescGZIP(), []int{4}
}

func (x *EnvVar) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *EnvVar) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Detailed server state information
type ServerState struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ServerId         string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Status           ServerStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=ironhost.v1.ServerStatus" json:"status,omitempty"`
	MemoryUsageBytes int64                  `protobuf:"varint,3,opt,name=memory_usage_bytes,json=memoryUsageBytes,proto3" json:"memory_usage_bytes,omitempty"`
	DiskUsageBytes   int64                  `protobuf:"varint,4,opt,name=disk_usage_bytes,json=diskUsageBytes,proto3" json:"disk_usage_bytes,omitempty"`
	CpuUsagePercent  float64                `protobuf:"fixed64,5,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`
	UptimeSeconds    int64                  `protobuf:"varint,6,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	LastUpdated      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ServerState) Reset() {
	*x = ServerState{}
	mi := &file_ironhost_v1_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerState) ProtoMessage() {}

func (x *ServerState) ProtoReflect() protoreflect.Message {
	mi := &file_ironhost_v1_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerState.ProtoReflect.Descriptor instead.
func (*ServerState) Descriptor() ([]byte, []int) {
	return file_ironhost_v1_common_proto_rawDescGZIP(), []int{5}
}

func (x *ServerState) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ServerState) GetStatus() ServerStatus {
	if x != nil {
		return x.Status
	}
	return ServerStatus_SERVER_STATUS_UNSPECIFIED
}

func (x *ServerState) GetMemoryUsageBytes() int64 {
	if x != nil {
		return x.MemoryUsageBytes
	}
	return 0
}

func (x *ServerState) GetDiskUsageBytes() int64 {
	if x != nil {
		return x.DiskUsageBytes
	}
	return 0
}

func (x *ServerState) GetCpuUsagePercent() float64 {
	if x != nil {
		return x.CpuUsagePercent
	}
	return 0
}

func (x *ServerState) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *ServerState) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

var File_ironhost_v1_common_proto protoreflect.FileDescriptor

const file_ironhost_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x18ironhost/v1/common.proto\x12\vironhost.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"/\n" +
	"\x10ServerIdentifier\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\")\n" +
	"\x0eNodeIdentifier\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"\x84\x01\n" +
	"\x0eResourceLimits\x12\x1b\n" +
	"\tmemory_mb\x18\x01 \x01(\x03R\bmemoryMb\x12\x17\n" +
	"\adisk_mb\x18\x02 \x01(\x03R\x06diskMb\x12\x1f\n" +
	"\vcpu_percent\x18\x03 \x01(\x05R\n" +
	"cpuPercent\x12\x1b\n" +
	"\tio_weight\x18\x04 \x01(\x05R\bioWeight\"n\n" +
	"\n" +
	"Allocation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x02 \x01(\tR\tipAddress\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x1d\n" +
	"\n" +
	"is_primary\x18\x04 \x01(\bR\tisPrimary\"0\n" +
	"\x06EnvVar\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xc7\x02\n" +
	"\vServerState\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x121\n" +
	"\x06status\x18\x02 \x01(\x0e2\x19.ironhost.v1.ServerStatusR\x06status\x12,\n" +
	"\x12memory_usage_bytes\x18\x03 \x01(\x03R\x10memoryUsageBytes\x12(\n" +
	"\x10disk_usage_bytes\x18\x04 \x01(\x03R\x0ediskUsageBytes\x12*\n" +
	"\x11cpu_usage_percent\x18\x05 \x01(\x01R\x0fcpuUsagePercent\x12%\n" +
	"\x0euptime_seconds\x18\x06 \x01(\x03R\ruptimeSeconds\x12=\n" +
	"\flast_updated\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated*\xd6\x01\n" +
	"\fServerStatus\x12\x1d\n" +
	"\x19SERVER_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18SERVER_STATUS_INSTALLING\x10\x01\x12\x19\n" +
	"\x15SERVER_STATUS_OFFLINE\x10\x02\x12\x1a\n" +
	"\x16SERVER_STATUS_STARTING\x10\x03\x12\x19\n" +
	"\x15SERVER_STATUS_RUNNING\x10\x04\x12\x1a\n" +
	"\x16SERVER_STATUS_STOPPING\x10\x05\x12\x1b\n" +
	"\x17SERVER_STATUS_SUSPENDED\x10\x06B'Z%github.com/ironhost/proto/ironhost/v1b\x06proto3"

var (
	file_ironhost_v1_common_proto_rawDescOnce sync.Once
	file_ironhost_v1_common_proto_rawDescData []byte
)

func file_ironhost_v1_common_proto_rawDescGZIP() []byte {
	file_ironhost_v1_common_proto_rawDescOnce.Do(func() {
		file_ironhost_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ironhost_v1_common_proto_rawDesc), len(file_ironhost_v1_common_proto_rawDesc)))
	})
	return file_ironhost_v1_common_proto_rawDescData
}

var file_ironhost_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ironhost_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_ironhost_v1_common_proto_goTypes = []any{
	(ServerStatus)(0),             // 0: ironhost.v1.ServerStatus
	(*ServerIdentifier)(nil),      // 1: ironhost.v1.ServerIdentifier
	(*NodeIdentifier)(nil),        // 2: ironhost.v1.NodeIdentifier
	(*ResourceLimits)(nil),        // 3: ironhost.v1.ResourceLimits
	(*Allocation)(nil),            // 4: ironhost.v1.Allocation
	(*EnvVar)(nil),                // 5: ironhost.v1.EnvVar
	(*ServerState)(nil),           // 6: ironhost.v1.ServerState
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_ironhost_v1_common_proto_depIdxs = []int32{
	0, // 0: ironhost.v1.ServerState.status:type_name -> ironhost.v1.ServerStatus
	7, // 1: ironhost.v1.ServerState.last_updated:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ironhost_v1_common_proto_init() }
func file_ironhost_v1_common_proto_init() {
	if File_ironhost_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ironhost_v1_common_proto_rawDesc), len(file_ironhost_v1_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ironhost_v1_common_proto_goTypes,
		DependencyIndexes: file_ironhost_v1_common_proto_depIdxs,
		EnumInfos:         file_ironhost_v1_common_proto_enumTypes,
		MessageInfos:      file_ironhost_v1_common_proto_msgTypes,
	}.Build()
	File_ironhost_v1_common_proto = out.File
	file_ironhost_v1_common_proto_goTypes = nil
	file_ironhost_v1_common_proto_depIdxs = nil
}
